---
- name: Setup Ubuntu Box
  hosts: localhost
  become: true
  tasks:
    - name: Apt Repositories
      apt_repository:
        repo: 'ppa:neovim-ppa/stable'
    - name: Apt Packages
      apt:
        state: latest
        name: "{{ item }}"
      loop:
        - htop
        - tree
        - neovim
    - name: Ripgrep
      apt:
        deb: https://github.com/BurntSushi/ripgrep/releases/download/0.8.1/ripgrep_0.8.1_amd64.deb
    - name: Install Pip Packages
      pip:
        name: "{{ item }}"
        state: present
      loop:
        - virtualenv
        - howdoi
        - neovim
    # - name: Install Npm Packages
    #   npm:
    #     name: "{{ item }}"
    #     global: yes
    #     state: present
    #   with_items:
    #     - lumo-cljs
    #     - serve
    #     - yarn
    #     - tldr
    #     - livereload
    # - name: Install Gems
    #   gem:
    #     name: "{{ item }}"
    #     state: present
    #   with_items:
    #     - pry
    #     - lolcat
    - name: Dotfiles Repo Is Present
      git:
        repo: https://github.com/zgulde/dotfiles
        clone: yes
        update: yes
        dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    - name: Dotfiles Are Installed
      file:
        state: link
        src: "{{ lookup('env', 'HOME') }}/dotfiles/{{ item[0] }}"
        dest: "{{ lookup('env', 'HOME') }}/{{ item[1] }}"
        with_items:
          - [bashrc, .bashrc]
          - [bash_profile, .bash_profile]
          - [aliases, .aliases]
          - [bash_functions, .bash_functions]
          - [gitconfig, .gitconfig]
          - [tmux.conf, .tmux.conf]
          - [editorconfig, .editorconfig]
          - [vimrc, .config/nvim/init.vim]
          - [snippets/vim, .config/nvim/UltiSnips]
          - [after, .config/nvim/after]
    - name: ~/.env file
      file:
        state: touch
        path: "{{ lookup('env', 'HOME') }}/.env"
    - name: Plugged (Neovim Plugin Manager)
      shell: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    - name: Editor Plugins
      shell: nvim -c PlugInstall -c q -c q
