---
- name: Setup Ubuntu Box
  hosts: localhost
  become: true
  tasks:
    - name: Install LinuxBrew
      shell: >
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
      creates: /home/linuxbrew/.linuxbrew
    - name: Apt Repositories
      apt_repository:
        repo: 'ppa:neovim-ppa/stable'
    - name: Apt Packages
      apt:
        state: latest
        name: "{{ item }}"
      loop:
        - htop
        - tree
        - neovim
    - name: Ripgrep and Pandoc (from debs)
      apt:
        deb: "{{ item }}"
      loop:
        - https://github.com/jgm/pandoc/releases/download/2.2.2.1/pandoc-2.2.2.1-1-amd64.deb
        - https://github.com/BurntSushi/ripgrep/releases/download/0.8.1/ripgrep_0.8.1_amd64.deb
    - name: Install Pip Packages
      pip:
        name: "{{ item }}"
        state: present
      loop:
        - virtualenv
        - howdoi
        - neovim

    # - name: Install Rust
    # - name: Node.js
    #   get_url:
    #     url: https://deb.nodesource.com/setup_10.x
    #     dest: /tmp
    # - name: Install Npm Packages
    #   npm:
    #     name: "{{ item }}"
    #     global: yes
    #     state: present
    #   with_items:
    #     - lumo-cljs
    #     - serve
    #     - yarn
    #     - tldr
    #     - livereload
    # - name: Install Gems
    #   gem:
    #     name: "{{ item }}"
    #     state: present
    #   with_items:
    #     - pry
    #     - lolcat
