---
- name: Neovim Intalled
  homebrew:
    name: neovim
    state: latest
- name: Plugged (Neovim Plugin Manager) Installed
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim
- name: Neovim Plugin Installation
  shell: nvim -c {{ item }} -c qa
  loop:
    - PlugInstall
    - PlugClean
    - PlugUpdate
